### PR TITLE
SwiftUI resource support for Image, Color, Font

### PR DESCRIPTION
**Pull request by apptekstudios**
Adds SwiftUI support. These additions are version gated, and make no breaking changes

### CODE REVIEW

**Comment by apptekstudios** [comment]
Thoughts on merging this into master?

**Comment by asam139** [comment]
I would be wonderful  😍

**Comment by piechart** [comment]
> Thoughts on merging this into master?

Yes please @mac-cain13 🙏

**Comment by sprzenus** [comment]
Will it be merged? It would be nice to have it 🧐

**Comment by domfz** [comment]
Nice!

**Comment by tomlokhorst** [comment]
Thanks for this PR!
Full SwiftUI support has been added to Rswift in version 7

**Pull request closed without merging**
