### PR TITLE
Add support for SPM with WatchOS platform

### PR DESCRIPTION
**Pull request by niorko**
Hello

We are migrating our project to SPM and we've found an issue with WatchOS platform with SPM.

The original approach was to create another WatchOS target and discard files from UIKit directory from that.
This approach can no longer be used for SPM, hence the PR.

Thanks

### CODE REVIEW

**Comment by fnuky** [comment]
Any progress in this PR? I would like to use it when migrating project to SPM..

**Comment by fnuky** [comment]
Is there any problem with MR?

**Comment by fnuky** [comment]
Could be this MR merged please?

**Comment by tomlokhorst** [comment]
@niorko Thank you for this PR!

**Pull request merged**
